gradle.beforeProject { project ->
    project.plugins.withId('com.android.application') {
        project.extensions.getByName('androidComponents').finalizeDsl { android ->
            android.defaultConfig.applicationId = 'com.chicory.redesign'
            android.buildTypes.release.manifestPlaceholders.usesCleartextTraffic = 'true'
        }
    }
}
